version: 2
jobs:
  build:
    macos:
      xcode: "12.3.0"
    steps:
      - checkout
      - run:
          name: Build and run unit tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Tracer
      - run:
          name: Build and run UI tests
          command: fastlane scan --workspace "Examples/TraceUIExample/TraceUIExample.xcworkspace"
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: TraceUIExample
      - run:
          name: Lint the pod
          command: pod lib lint --allow-warnings
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
